# Generated by Django 4.1 on 2022-08-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('CatId', models.AutoField(primary_key=True, serialize=False)),
                ('CatName', models.CharField(max_length=500)),
                ('Age', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DateOfArrival', models.CharField(max_length=500)),
                ('Needs', models.CharField(max_length=1000)),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('EmployeePosition', models.CharField(max_length=500)),
                ('StartDate', models.CharField(max_length=500)),
                ('Pay', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
