# Generated by Django 4.1 on 2022-08-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeePosition',
            new_name='Position',
        ),
    ]
