# Generated by Django 4.1 on 2022-09-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0003_alter_cats_dateofarrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='StartDate',
            field=models.DateField(),
        ),
    ]
