# Generated by Django 4.1 on 2022-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0004_alter_employees_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='DateOfArrival',
            field=models.DateField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='employees',
            name='StartDate',
            field=models.DateField(verbose_name=''),
        ),
    ]
