# Generated by Django 4.1 on 2022-09-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0005_alter_cats_dateofarrival_alter_employees_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='DateOfArrival',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='employees',
            name='StartDate',
            field=models.CharField(max_length=500),
        ),
    ]
